### PR TITLE
fix

### PR DESCRIPTION
**Pull request by adhu2018**
修复caj以外格式的支持

### CODE REVIEW

**Review by qinlili23333 — APPROVED** [review]

**Comment by HinTak** [comment]
The change is not quite correct; also the description of the problem is lacking: there is a genuine bug that caj2pdf would overwrite the input file if it does not ends with ".caj". I have encountered that myself, and accidentally overwritten my input file a few times.

The fix is not quite correct as files do not need to have extensions, and can have multiple dots in the name too. I would suggest (1) checks that it ends with ".caj" before making the output name, (2) appends ".pdf" if the name does not have a dot, or generally just append, (3) check the the generated "*.pdf" does not exist.

Not sure about (3) as I think the outlines etc code requires overwriting existing pdf files, I think. But I think switching from substitute to split on ext is just have a different set of problems (file names not having dots)

**Comment by adhu2018** [comment]
> The change is not quite correct; also the description of the problem is lacking: there is a genuine bug that caj2pdf would overwrite the input file if it does not ends with ".caj". I have encountered that myself, and accidentally overwritten my input file a few times.
> 
> The fix is not quite correct as files do not need to have extensions, and can have multiple dots in the name too. I would suggest (1) checks that it ends with ".caj" before making the output name, (2) appends ".pdf" if the name does not have a dot, or generally just append, (3) check the the generated "*.pdf" does not exist.
> 
> Not sure about (3) as I think the outlines etc code requires overwriting existing pdf files, I think. But I think switching from substitute to split on ext is just have a different set of problems (file names not having dots)

This is not my project, I think it is best not to change the original idea of the code, so the less changes the better.

**Comment by qinlili23333** [comment]
> The change is not quite correct; also the description of the problem is lacking: there is a genuine bug that caj2pdf would overwrite the input file if it does not ends with ".caj". I have encountered that myself, and accidentally overwritten my input file a few times.
> 
> The fix is not quite correct as files do not need to have extensions, and can have multiple dots in the name too. I would suggest (1) checks that it ends with ".caj" before making the output name, (2) appends ".pdf" if the name does not have a dot, or generally just append, (3) check the the generated "*.pdf" does not exist.
> 
> Not sure about (3) as I think the outlines etc code requires overwriting existing pdf files, I think. But I think switching from substitute to split on ext is just have a different set of problems (file names not having dots)

i think just simply add ".pdf" at the end of filename is the best solution.
just like below:
"123.caj" -> "123.caj.pdf"
"123" -> "123.pdf"
"123.hn" -> "123.hn.pdf"

**Comment by HinTak** [comment]
I have merged after added on it as I outlined - we forgot the input could be a ".pdf" file too, im which case it should not do splitext either. Anyway, I think the current code cope with all cases: ends with caj, ends with .* but not .pdf; append if file name too short , ends with .pdf, or without extension.

**Pull request merged**
