### PR TITLE
FixBugs(requirements.txt): 加入 typing_extensions 包

### PR DESCRIPTION
**Pull request by zhuyuanxiang**
我用Conda安装，需要三个包才行

### CODE REVIEW

**Comment by HinTak** [comment]
There is no direct dependency of caj2pdf on type_extensions; however, pip and setuptools both have a private copy of it, so it is likely conda needs it to manage packages. In any case, since pip and setup tools both depends on type_extensions, it is already implicit that which ever way you install, your install tool needs it.

I don't feel too strongly either way, but since there is no explicit dependency, I am going to close this. Unless you can point out any indirect dependency, like  img2pdf needs it, etc.

**Comment by HinTak** [comment]
What I mean is, conda needs type_extensions, or pip needs type_extensions, is a different matter as caj2pdf needing it.

**Comment by zhuyuanxiang** [comment]
When I use pip install PyPDF2, typing-extensions will install automatically.
When I use conda install pypdf2, typing-extensions will install independently.

**Comment by HinTak** [comment]
That's a issue with conda, I think.

**Comment by zhuyuanxiang** [comment]
I think so.
I makred here for others.

**Pull request closed without merging**
